#!/bin/sh

#PBS -l nodes=4:ppn=32,walltime=01:00:00
#PBS -N XiaofanHPC3
#PBS -M xsun042@ucr.edu

module purge
module load gcc-4.7.2
module load mvapich2-1.9/gcc-4.7.2

JOB_PATH=/home/xsun042/ProjectHPC3/
cd $JOB_PATH
make
make run
